### ISSUE TITLE
How to properly send back the RUPX from VPN MasterNodes to one address before the Fork

### ISSUE THREAD

**Issue by rocky3xr** [rupaya-project/documentation#11]
Hello everyone,

I cant' find a guide on how to properly do all this things before the fork.
From the wallet, using coin control, I've send all the coins to 1 address, however the coins in the MasterNodes are locked with the lock symbol. My question  is what I have to do and how I have to do.

**Comment by theDavidCoen** [comment]
Check this: https://medium.com/@rupaya/rupaya-community-update-september-11-2018-88c16fd1ecb8
