### ISSUE TITLE
On VPS I'm getting below error "Masternode not found in the list of available masternodes"

### ISSUE THREAD

**Issue by shailysingh1975** [rupaya-project/documentation#2]
Please help I'm getting below error on VPS 

# rupaya-cli masternode status
error: {"code":-1,"message":"Masternode not found in the list of available masternodes. Current status: Not capable masternode: Hot node, waiting for remote activation."}

**Comment by Remapper** [comment]
Not enough info, please check the discord channel and follow masternode setup guodes

**Comment by rupaya-project** [comment]
Please go throught the masternode setup guide again

**Comment by tech1e** [comment]
Give it more time after both cold and hot wallets are in sync. It takes 20 mins or so before the activation goes through. Please reopen if you still have issues. Thank you.
