### ISSUE TITLE
No block source available 

### ISSUE THREAD

**Issue by nad010286** [rupaya-project/documentation#5]
I download the Wallet for MACOS and got this. Wallet doesn't sync

**Comment by bjorntheart** [comment]
@nad010286 Wallet issues should be addressed in the coin repository here https://github.com/rupaya-project/rupaya. Even better, jump on Rupaya's Discord channel and ask the developers or community in there for help. They are very responsive and helpful. Rupaya has a great community. Here is the link to Rupay's Discord channel https://github.com/rupaya-project/rupaya
